// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"time"
)

type User struct {
	ID        uint32
	FirstName string
	LastName  string
	Email     string
	Password  string
	Createdat time.Time
	Updatedat time.Time
}
